Mandos real gas
ElrondNetwork/arwen-wasm-vm pull request #266
Opened 2021-03-09 04:57 UTC by andrei-marinica

2021-03-12 11:16 UTC, sasurobert requested changes

2021-03-12 11:16 UTC, sasurobert commented on mandos-go/json/model/gasSchedule.go
> +	GasScheduleDummy GasSchedule = iota
why do you have iota 2 times ?

2021-03-12 11:29 UTC, andrei-marinica commented on mandos-go/json/model/gasSchedule.go
> +	GasScheduleDummy GasSchedule = iota
bad copy paste, fixing now

2021-03-15 12:04 UTC, sasurobert approved these changes

2021-03-16 09:31 UTC, camilbancioiu approved these changes

2021-03-16 10:05 UTC, merged