Revert using blockchainhook
ElrondNetwork/arwen-wasm-vm pull request #309
Opened 2021-05-28 17:00 UTC by matei-p

2021-06-01 12:59 UTC, sasurobert requested changes

2021-06-01 12:59 UTC, sasurobert commented on arwen/host/execution.go
> +	blockchain := host.Blockchain()
we have to delete any user of RevertESDT - there are 2 public functions. those must deleted

2021-06-01 12:59 UTC, sasurobert commented on go.sum
> +github.com/ElrondNetwork/elrond-go v1.2.1-0.20210531130414-6ceb2ade721d h1:3/diuAqRtbVSE8twOjfnDQrhOrnpiiIyDSnVzcDfJvo=
go mod tidy

2021-06-01 12:59 UTC, sasurobert commented on ipc/arwenpart/blockchainGateway.go
> +	"github.com/ElrondNetwork/elrond-go/data/esdt"
sort imports

2021-06-01 12:59 UTC, sasurobert commented on ipc/arwenpart/blockchainGateway.go
> +
this is wrong. There is no need for IPC messaging for IsInterfaceNil. the only code here should be return blockchain == nil

2021-06-01 12:59 UTC, sasurobert commented on mock/context/blockChainHookStub.go
> +// GetSnapshot mocked method
should be moved before IsInterfaceNIl

2021-06-01 12:59 UTC, sasurobert commented on arwen/host/execution.go
> +	blockchain := host.Blockchain()
you have to remove host.RevertESDTTransfer(input) from TransferAndExecute function. Now you revert it through snapshot. after that you send tokens again.

2021-06-01 13:00 UTC, sasurobert commented on arwen/host/execution.go
> +	blockchain := host.Blockchain()
the same happens on asnycCall with revert -> you make a revert snasphot here, but you make and actual transfer later - which is clearly wrong.

2021-06-03 06:53 UTC, matei-p commented on go.sum
> +github.com/ElrondNetwork/elrond-go v1.2.1-0.20210531130414-6ceb2ade721d h1:3/diuAqRtbVSE8twOjfnDQrhOrnpiiIyDSnVzcDfJvo=
did not produce any change in go.sum

2021-06-04 07:10 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
> +			_ = arwen.WithFaultAndHost(host, arwen.WrapError(executeErr).WrapWithError(executeErr), true)
no arwenWithFault here.

2021-06-04 07:10 UTC, sasurobert commented on arwen/host/asyncCall.go
> +			isESDTTransfer, _, _ := isESDTTransferOnReturnDataFromFunctionAndArgs(functionName, args)
good refactor.

2021-06-04 07:28 UTC, sasurobert approved these changes

2021-06-04 09:18 UTC, sasurobert commented on arwen/contexts/blockchain.go
> +func (context *blockchainContext) GetSnapshot() int {
add comment to public function

2021-06-04 09:18 UTC, sasurobert commented on arwen/contexts/blockchain.go
> +func (context *blockchainContext) RevertToSnapshot(snapshot int) {
add comment to public function

2021-06-04 09:25 UTC, sasurobert approved these changes

2021-06-04 16:01 UTC, camilbancioiu approved these changes

2021-06-04 16:02 UTC, merged