Deploy and Upgrade contract API on Arwen
ElrondNetwork/arwen-wasm-vm pull request #329
Opened 2021-06-16 12:10 UTC by matei-p

2021-06-18 09:12 UTC, camilbancioiu requested changes
Only requirement: `upgradeContract()` has been changed on `master`. Make sure the new `upgradeFromSourceContract()` is also updated in the same way.

2021-06-18 09:59 UTC, matei-p commented on arwen/elrondapi/elrondei.go
> +	gasToUse := metering.GasSchedule().ElrondAPICost.CreateContract
No

2021-06-21 08:17 UTC, camilbancioiu requested changes

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +	newAddress, err := createContractCall(sender, data, valueAsInt, metering, gasLimit, code, codeMetadata, host, runtime)
Consider renaming to `createContract()`

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +func v1_3_upgradeFromSourceContract(
This API function must also take the code metadata, just like `upgradeContract` does.

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +) int32 {
Must also take `codeMetadata` as parameter, regardless of what the source contract has.

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +	codeMetadata := contract.GetCodeMetadata()
Use metadata provided as parameter at runtime instead.

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/hosttest/execution_test.go
> +
Forgotten logging setup.

2021-06-21 08:17 UTC, camilbancioiu commented on arwen/elrondapi/elrondei.go
> +	gasLimit int64,
Must take `codeMetadata` as parameter, coming from the caller contract.

2021-06-21 08:43 UTC, camilbancioiu approved these changes

2021-06-21 08:51 UTC, andrei-marinica approved these changes

2021-06-21 08:52 UTC, merged