Managed Buffers context + unit tests
ElrondNetwork/arwen-wasm-vm pull request #348
Opened 2021-07-09 13:29 UTC by andrei-diaconescu

"feat/man-buffers" is the feature branch

I would've renamed "feat/managed-buffers" with "man-buffers-context" or something but couldn't anymore because of rules changed on Github. Will delete the "feat/managed-buffers" after merge in feature branch

2021-07-14 06:57 UTC, sasurobert requested changes

2021-07-14 06:57 UTC, sasurobert commented on arwen/contexts/managedType.go
> +func (context *managedTypesContext) SetBytesForThisManagedBuffer(manBufHandle int32, bytes []byte) int32 {
I think something is missing from this PR. Like the EI / API functions ?

2021-07-16 07:40 UTC, sasurobert approved these changes

2021-07-19 06:58 UTC, andrei-marinica approved these changes

2021-07-19 08:25 UTC, merged