Random managed buffers
ElrondNetwork/arwen-wasm-vm pull request #387
Opened 2021-08-11 12:38 UTC by andrei-diaconescu

2021-08-11 12:46 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	if length < 1 {
_ = arwen.WithFault

2021-08-11 12:46 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	metering.UseGas(baseGasToUse + lengthDependentGasToUse)
you have to use math.AddUint64

2021-08-11 12:46 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	baseGasToUse := metering.GasSchedule().ManagedBufferAPICost.MBufferNewFromBytes
use MBufferNewRandom instead

2021-08-11 12:46 UTC, sasurobert commented on arwen/elrondapi/manBufOps.go
> +	randomizer := managedType.GetRandReader()
one more change for getRandReader - make it use previous block randomness, current block randomness and tx hash

2021-08-11 13:17 UTC, sasurobert commented on arwen/contexts/managedType.go
> +	randomizer := math.NewSeedRandReader(append(append(context.host.Blockchain().CurrentRandomSeed(), context.host.Runtime().GetCurrentTxHash()...), context.host.Blockchain().LastRandomSeed()...))
beutify this please.

2021-08-12 08:01 UTC, andrei-marinica requested changes

2021-08-12 08:37 UTC, camilbancioiu submitted a review, later dismissed

2021-08-12 08:39 UTC, andrei-marinica commented on test/contracts/managed-buffers/managed-buffers.c
> +        int handle = mBufferNew();
I mentioned above but not for all of them, I think the best way would be to return the resulting buffers themselves, using `mBufferFinish`

2021-08-12 17:01 UTC, andrei-marinica submitted a review, later dismissed

2021-08-13 09:21 UTC, sasurobert submitted a review, later dismissed

2021-08-13 12:11 UTC, sasurobert approved these changes

2021-08-13 12:24 UTC, andrei-marinica approved these changes

2021-08-13 12:34 UTC, merged