Fix returns, bugs, little refactor in APIs
ElrondNetwork/arwen-wasm-vm pull request #391
Opened 2021-08-18 14:41 UTC by andrei-diaconescu

2021-08-18 15:39 UTC, sasurobert requested changes

2021-08-18 15:39 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
>  		arwen.WithFault(arwen.ErrNonPayableFunctionEgld, context, runtime.ElrondAPIErrorShouldFailExecution())
_ =

2021-08-18 15:39 UTC, sasurobert commented on arwen/elrondapi/elrondei.go
>  		arwen.WithFault(arwen.ErrNonPayableFunctionEsdt, context, runtime.ElrondAPIErrorShouldFailExecution())
_ =

2021-08-18 15:47 UTC, sasurobert approved these changes

2021-08-19 08:43 UTC, camilbancioiu requested changes

2021-08-19 08:43 UTC, camilbancioiu commented on test/contracts/exec-dest-ctx-builtin/elrond.json
> +        "/home/andrei/arwen-wasm-vm/test/contracts/exec-dest-ctx-builtin/exec-dest-ctx-builtin.c"
Path contains local folder structure with username. Please anonymize.

2021-08-19 08:58 UTC, camilbancioiu approved these changes

2021-08-19 09:00 UTC, sasurobert approved these changes

2021-08-19 09:00 UTC, merged